mysql-backup:
  container_name: mysql-backup
  # image: kitpages/mysql-backup
  build: .

docker-gen:
  container_name: mysql-backup-dg
  image: jwilder/docker-gen
  entrypoint: docker-gen -notify-sighup mysql-backup -watch /backup-scripts/backup-all.sh.tmpl /backup-scripts/backup-all.sh
  volumes_from:
    - mysql-backup
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
